<?php
if(isset($_GET['xd1xd1'])){
$con=mysql_connect("localhost","root","xd22xd22");
mysql_select_db("modules");
mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('A1','Anonymous Proxy')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('A2','Satellite Provider')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('O1','Other Country')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AD','Andorra')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AE','United Arab Emirates')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AF','Afghanistan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AG','Antigua and Barbuda')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AI','Anguilla')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AL','Albania')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AM','Armenia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AO','Angola')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AP','Asia/Pacific Region')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AQ','Antarctica')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AR','Argentina')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AS','American Samoa')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AT','Austria')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AU','Australia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AW','Aruba')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AX','Aland Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('AZ','Azerbaijan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BA','Bosnia and Herzegovina')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BB','Barbados')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BD','Bangladesh')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BE','Belgium')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BF','Burkina Faso')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BG','Bulgaria')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BH','Bahrain')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BI','Burundi')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BJ','Benin')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BL','Saint Bartelemey')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BM','Bermuda')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BN','Brunei Darussalam')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BO','Bolivia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BQ','Bonaire, Saint Eustatius and Saba')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BR','Brazil')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BS','Bahamas')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BT','Bhutan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BV','Bouvet Island')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BW','Botswana')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BY','Belarus')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('BZ','Belize')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CA','Canada')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CC','Cocos (Keeling) Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CD','Congo, The Democratic Republic of the')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CF','Central African Republic')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CG','Congo')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CH','Switzerland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CI','Cote d\'Ivoire')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CK','Cook Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CL','Chile')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CM','Cameroon')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CN','China')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CO','Colombia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CR','Costa Rica')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CU','Cuba')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CV','Cape Verde')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CW','Curacao')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CX','Christmas Island')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CY','Cyprus')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('CZ','Czech Republic')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('DE','Germany')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('DJ','Djibouti')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('DK','Denmark')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('DM','Dominica')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('DO','Dominican Republic')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('DZ','Algeria')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('EC','Ecuador')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('EE','Estonia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('EG','Egypt')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('EH','Western Sahara')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ER','Eritrea')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ES','Spain')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ET','Ethiopia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('EU','Europe')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('FI','Finland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('FJ','Fiji')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('FK','Falkland Islands (Malvinas)')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('FM','Micronesia, Federated States of')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('FO','Faroe Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('FR','France')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GA','Gabon')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GB','United Kingdom')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GD','Grenada')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GE','Georgia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GF','French Guiana')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GG','Guernsey')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GH','Ghana')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GI','Gibraltar')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GL','Greenland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GM','Gambia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GN','Guinea')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GP','Guadeloupe')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GQ','Equatorial Guinea')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GR','Greece')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GS','South Georgia and the South Sandwich Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GT','Guatemala')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GU','Guam')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GW','Guinea-Bissau')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('GY','Guyana')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('HK','Hong Kong')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('HM','Heard Island and McDonald Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('HN','Honduras')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('HR','Croatia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('HT','Haiti')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('HU','Hungary')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ID','Indonesia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IE','Ireland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IL','Israel')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IM','Isle of Man')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IN','India')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IO','British Indian Ocean Territory')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IQ','Iraq')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IR','Iran, Islamic Republic of')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IS','Iceland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('IT','Italy')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('JE','Jersey')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('JM','Jamaica')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('JO','Jordan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('JP','Japan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KE','Kenya')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KG','Kyrgyzstan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KH','Cambodia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KI','Kiribati')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KM','Comoros')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KN','Saint Kitts and Nevis')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KP','Korea, Democratic People\'s Republic of')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KR','Korea, Republic of')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KW','Kuwait')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KY','Cayman Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('KZ','Kazakhstan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LA','Lao People\'s Democratic Republic')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LB','Lebanon')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LC','Saint Lucia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LI','Liechtenstein')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LK','Sri Lanka')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LR','Liberia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LS','Lesotho')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LT','Lithuania')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LU','Luxembourg')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LV','Latvia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('LY','Libyan Arab Jamahiriya')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MA','Morocco')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MC','Monaco')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MD','Moldova, Republic of')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ME','Montenegro')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MF','Saint Martin')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MG','Madagascar')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MH','Marshall Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MK','Macedonia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ML','Mali')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MM','Myanmar')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MN','Mongolia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MO','Macao')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MP','Northern Mariana Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MQ','Martinique')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MR','Mauritania')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MS','Montserrat')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MT','Malta')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MU','Mauritius')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MV','Maldives')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MW','Malawi')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MX','Mexico')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MY','Malaysia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('MZ','Mozambique')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NA','Namibia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NC','New Caledonia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NE','Niger')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NF','Norfolk Island')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NG','Nigeria')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NI','Nicaragua')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NL','Netherlands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NO','Norway')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NP','Nepal')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NR','Nauru')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NU','Niue')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('NZ','New Zealand')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('OM','Oman')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PA','Panama')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PE','Peru')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PF','French Polynesia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PG','Papua New Guinea')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PH','Philippines')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PK','Pakistan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PL','Poland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PM','Saint Pierre and Miquelon')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PN','Pitcairn')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PR','Puerto Rico')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PS','Palestinian Territory')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PT','Portugal')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PW','Palau')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('PY','Paraguay')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('QA','Qatar')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('RE','Reunion')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('RO','Romania')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('RS','Serbia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('RU','Russian Federation')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('RW','Rwanda')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SA','Saudi Arabia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SB','Solomon Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SC','Seychelles')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SD','Sudan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SE','Sweden')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SG','Singapore')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SH','Saint Helena')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SI','Slovenia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SJ','Svalbard and Jan Mayen')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SK','Slovakia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SL','Sierra Leone')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SM','San Marino')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SN','Senegal')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SO','Somalia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SR','Suriname')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ST','Sao Tome and Principe')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SV','El Salvador')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SX','Sint Maarten')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SY','Syrian Arab Republic')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('SZ','Swaziland')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TC','Turks and Caicos Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TD','Chad')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TF','French Southern Territories')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TG','Togo')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TH','Thailand')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TJ','Tajikistan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TK','Tokelau')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TL','Timor-Leste')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TM','Turkmenistan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TN','Tunisia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TO','Tonga')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TR','Turkey')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TT','Trinidad and Tobago')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TV','Tuvalu')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TW','Taiwan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('TZ','Tanzania, United Republic of')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('UA','Ukraine')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('UG','Uganda')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('UM','United States Minor Outlying Islands')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('US','United States')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('UY','Uruguay')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('UZ','Uzbekistan')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VA','Holy See (Vatican City State)')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VC','Saint Vincent and the Grenadines')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VE','Venezuela')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VG','Virgin Islands, British')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VI','Virgin Islands, U.S.')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VN','Vietnam')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('VU','Vanuatu')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('WF','Wallis and Futuna')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('WS','Samoa')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('YE','Yemen')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('YT','Mayotte')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ZA','South Africa')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ZM','Zambia')");mysql_query("INSERT INTO countries (countryc,countryn)
VALUES ('ZW','Zimbabwe')");
mysql_close($con);
}
?>