<?php
$secho='
var validext=new Array();
validext[0]="3g2"; // (Mobile Video)
validext[1]="3gp"; // (Mobile Video)
validext[2]="3gpp"; // (Mobile Video)
validext[3]="asf"; // (Windows Media Video)
validext[4]="avi"; // (AVI Video)
validext[5]="dat"; // (MPEG Video)
validext[6]="divx"; // (DIVX Video)
validext[7]="dv"; // (DV Video)
validext[8]="f4v"; // (Flash Video)
validext[9]="flv"; // (Flash Video)
validext[10]="m2ts"; // (M2TS Video)
validext[11]="m4v"; // (MPEG-4 Video)
validext[12]="mkv"; // (Matroska Format)
validext[13]="mod"; // (MOD Video)
validext[14]="mov"; // (QuickTime Movie)
validext[15]="mp4"; // (MPEG-4 Video)
validext[16]="mpe"; // (MPEG Video)
validext[17]="mpeg"; // (MPEG Video)
validext[18]="mpeg4"; // (MPEG-4 Video)
validext[19]="mpg"; // (MPEG Video)
validext[20]="mts"; // (AVCHD Video)
validext[21]="nsv"; // (Nullsoft Video)
validext[22]="ogm"; // (Ogg Media Format)
validext[23]="ogv"; // (Ogg Video Format)
validext[24]="qt"; // (QuickTime Movie)
validext[25]="tod"; // (TOD Video)
validext[26]="ts"; // (MPEG Transport Stream)
validext[27]="vob"; // (DVD Video)
validext[28]="wmv"; // (Windows Media Video)
';
?>