<?php
$sl=explode("@",$nemail);
$sl=$sl[1];

$p=array();
$p['m']='<table style="border-collapse:collapse;width:98%" cellpadding="0" cellspacing="0" border="0"><tr><td style="font-size:12px;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif"><table style="border-collapse:collapse;width:620px" cellpadding="0" cellspacing="0"><tr><td style="font-size:16px;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif;background:#3b5998;color:#ffffff;font-weight:bold;vertical-align:baseline;letter-spacing:-0.03em;text-align:left;padding:5px 20px"><a style="text-decoration:none" href="http://localhost" target="_blank"><span style="background:#3b5998;color:#ffffff;font-weight:bold;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif;vertical-align:middle;font-size:16px;letter-spacing:-0.03em;text-align:left;vertical-align:baseline">upfrev</span></a></td></tr></table><table style="border-collapse:collapse;width:620px" cellpadding="0" cellspacing="0" border="0" width="620px"><tr><td style="padding:0px;background-color:#f2f2f2;border-left:none;border-right:none;border-top:none;border-bottom:none"><table style="border-collapse:collapse" cellpadding="0" cellspacing="0" width="620px"><tr><td style="font-size:11px;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif;padding:0px;width:620px"><table style="border-collapse:collapse;width:100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:20px;background-color:#fff;border-left:none;border-right:none;border-top:none;border-bottom:none"><table style="border-collapse:collapse;width:100%" cellpadding="0" cellspacing="0"><tr><td style="font-size:11px;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif;padding-bottom:10px"><span style="color:#333333">To verify your @<a href="http://'.$sl.'" target="_blank">'.$sl.'</a> address, please follow this link<br><a href="http://www.subsbook.com/confirmcontact.php?c='.$c.'&amp;x=1&amp;gfid='.$gfid.'" style="color:#3b5998;text-decoration:none" target="_blank">/confirmcontact.php?c='.$c.'&amp;x=1&amp;gfid='.$gfid.'</a></span></td></tr><tr><td style="font-size:11px;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif;padding-top:10px;padding-bottom:10px"><span style="color:#333333">If you did not enter this address as your contact email, please disregard this message.</span></td></tr></table></td></tr></table></td></tr><tr><td style="font-size:11px;font-family:\'lucida grande\',tahoma,verdana,arial,sans-serif;padding:0px;width:620px"><table style="border-collapse:collapse" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:0;background-color:#fff;border-left:none;border-right:none;border-top:1px solid #ccc;border-bottom:none"></td></tr></table></td></tr></table></td></tr></table><span style="width:620px"><img src="/images/transparent.png" style="border:0;width:1px;min-height:1px"><u></u></span></td></tr></table>';

$p['f']="Upfrev";
$p['e']="no-reply@subsbook.com";
$p['t']=$nemail;
$p['s']='Upfrev Email Verification';

sbmail($p,false);
?>